<?php
/**
 * Created by IntelliJ IDEA.
 * User: DenysBarsuk
 * Date: 11.06.2018
 * Time: 11:11
 */

namespace Schedule\Core\Models;


use Phalcon\Mvc\Model;
use Schedule\Core\Location;

class TransitRoutes extends Model
{
    /**
     * @var int
     */
    private $id;
    /**
     * @var int
     */
    private $from_id_station;
    /**
     * @var int
     */
    private $to_id_station;
    /**
     * @var \DateTime
     */
    private $arrival;
    /**
     * @var \DateTime
     */
    private $departure;
    /**
     * @var int
     */
    private $belongs_to_route;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getFromIdStation()
    {
        return $this->from_id_station;
    }

    /**
     * @param int|Location $from_id_station
     */
    public function setFromIdStation($from_id_station)
    {
        $this->from_id_station = $from_id_station;
    }

    /**
     * @return int
     */
    public function getToIdStation()
    {
        return $this->to_id_station;
    }

    /**
     * @param int $to_id_station
     */
    public function setToIdStation($to_id_station)
    {
        $this->to_id_station = $to_id_station;
    }

    /**
     * @return \DateTime
     */
    public function getArrival()
    {
        return $this->arrival;
    }

    /**
     * @param \DateTime $arrival
     */
    public function setArrival($arrival)
    {
        $this->arrival = $arrival;
    }

    /**
     * @return \DateTime
     */
    public function getDeparture()
    {
        return $this->departure;
    }

    /**
     * @param \DateTime $departure
     */
    public function setDeparture($departure)
    {
        $this->departure = $departure;
    }

    /**
     * @return int
     */
    public function getBelongsToRoute()
    {
        return $this->belongs_to_route;
    }

    /**
     * @param int $belongs_to_route
     */
    public function setBelongsToRoute($belongs_to_route)
    {
        $this->belongs_to_route = $belongs_to_route;
    }

    /**
     * @param null $parameters
     * @return TransitRoutes
     */
    public static function findFirst($parameters = null)
    {
      return   parent::findFirst($parameters); // TODO: Change the autogenerated stub
    }

    public function getSource()
    {
        return 'transit_routes';
    }
}